# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mabe/Escritorio/ESTACION-PRO

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mabe/Escritorio/ESTACION-PRO

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package
.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/mabe/Escritorio/ESTACION-PRO/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mabe/Escritorio/ESTACION-PRO/CMakeFiles /home/mabe/Escritorio/ESTACION-PRO//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mabe/Escritorio/ESTACION-PRO/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named localization

# Build rule for target.
localization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 localization
.PHONY : localization

# fast build rule for target.
localization/fast:
	$(MAKE) $(MAKESILENT) -f locale/CMakeFiles/localization.dir/build.make locale/CMakeFiles/localization.dir/build
.PHONY : localization/fast

#=============================================================================
# Target rules for targets named es-pdf-convert

# Build rule for target.
es-pdf-convert: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 es-pdf-convert
.PHONY : es-pdf-convert

# fast build rule for target.
es-pdf-convert/fast:
	$(MAKE) $(MAKESILENT) -f es-pdf-converter/CMakeFiles/es-pdf-convert.dir/build.make es-pdf-converter/CMakeFiles/es-pdf-convert.dir/build
.PHONY : es-pdf-convert/fast

#=============================================================================
# Target rules for targets named lunasvg

# Build rule for target.
lunasvg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lunasvg
.PHONY : lunasvg

# fast build rule for target.
lunasvg/fast:
	$(MAKE) $(MAKESILENT) -f external/lunasvg/CMakeFiles/lunasvg.dir/build.make external/lunasvg/CMakeFiles/lunasvg.dir/build
.PHONY : lunasvg/fast

#=============================================================================
# Target rules for targets named plutovg

# Build rule for target.
plutovg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 plutovg
.PHONY : plutovg

# fast build rule for target.
plutovg/fast:
	$(MAKE) $(MAKESILENT) -f external/lunasvg/plutovg/CMakeFiles/plutovg.dir/build.make external/lunasvg/plutovg/CMakeFiles/plutovg.dir/build
.PHONY : plutovg/fast

#=============================================================================
# Target rules for targets named svg2png

# Build rule for target.
svg2png: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 svg2png
.PHONY : svg2png

# fast build rule for target.
svg2png/fast:
	$(MAKE) $(MAKESILENT) -f external/lunasvg/examples/CMakeFiles/svg2png.dir/build.make external/lunasvg/examples/CMakeFiles/svg2png.dir/build
.PHONY : svg2png/fast

#=============================================================================
# Target rules for targets named rlottie

# Build rule for target.
rlottie: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rlottie
.PHONY : rlottie

# fast build rule for target.
rlottie/fast:
	$(MAKE) $(MAKESILENT) -f external/rlottie/CMakeFiles/rlottie.dir/build.make external/rlottie/CMakeFiles/rlottie.dir/build
.PHONY : rlottie/fast

#=============================================================================
# Target rules for targets named lottie2gif

# Build rule for target.
lottie2gif: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lottie2gif
.PHONY : lottie2gif

# fast build rule for target.
lottie2gif/fast:
	$(MAKE) $(MAKESILENT) -f external/rlottie/example/CMakeFiles/lottie2gif.dir/build.make external/rlottie/example/CMakeFiles/lottie2gif.dir/build
.PHONY : lottie2gif/fast

#=============================================================================
# Target rules for targets named es-core

# Build rule for target.
es-core: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 es-core
.PHONY : es-core

# fast build rule for target.
es-core/fast:
	$(MAKE) $(MAKESILENT) -f es-core/CMakeFiles/es-core.dir/build.make es-core/CMakeFiles/es-core.dir/build
.PHONY : es-core/fast

#=============================================================================
# Target rules for targets named ESTACION-PRO

# Build rule for target.
ESTACION-PRO: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ESTACION-PRO
.PHONY : ESTACION-PRO

# fast build rule for target.
ESTACION-PRO/fast:
	$(MAKE) $(MAKESILENT) -f es-app/CMakeFiles/ESTACION-PRO.dir/build.make es-app/CMakeFiles/ESTACION-PRO.dir/build
.PHONY : ESTACION-PRO/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... localization"
	@echo "... ESTACION-PRO"
	@echo "... es-core"
	@echo "... es-pdf-convert"
	@echo "... lottie2gif"
	@echo "... lunasvg"
	@echo "... plutovg"
	@echo "... rlottie"
	@echo "... svg2png"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

